### PR TITLE
Add font #4 'fontlargeletter31x48'

### PR DESCRIPTION
**Pull request by DaAwesomeP**
This font is the full height of the screen. I also added a section to the example file.

If you wouldn't mind, please make a new release rather soon. I'm going to put my project (which utilizes this font) in a contest soon and it would be more complicated to have to instruct how to apply a patch like this.

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
The contest ends today, so a merge would be much appreciated.

**Comment by jimblom** [comment]
Looks awesome. Thanks for contributing!

Good luck in the contest :).

**Comment by DaAwesomeP** [comment]
Thanks!

**Comment by DaAwesomeP** [comment]
@jimblom if you wouldn't mind creating a new tag and release, then that would be great. That way it will get pushed to the Arduino Library Manager.

**Comment by jimblom** [comment]
I may have been a little hasty pulling this in.

The large letter font looks great, but I didn't realize it uses a huge chunk of flash -- about 7k. I don't want to hamstring an ATmega328's program memory capacity with this library more than it already is, so I've added some flags to disable the font by default.

For now, to enable the large letter font, uncomment out [this line](https://github.com/sparkfun/SparkFun_Micro_OLED_Arduino_Library/blob/master/src/SFE_MicroOLED.cpp#L46).

**Pull request merged**
